#!/Users/kamal/.asdf/shims/ruby

require 'csv'
require 'bundler/inline'

gemfile do
  source "https://rubygems.org"
  gem 'lmdb', '~> 0.6.2'
end

TOTAL_LINES = 660_146_231.0

LMDB.new("./database", mapsize: 10 * 1024 * 1024) do |env|
  db = env.database

  IO.popen("zless #{ARGV[0]}", "r") do |pipe|
    pipe.each.with_index do |line, i|
      next if line =~ /^#/
      id, ref = line.split("\t").values_at(*[2, 3])
      env.transaction { db[id] = ref }
      print "\rProgress: #{100 * i / TOTAL_LINES}%..."
    end
  end
end
