#!/Users/kamal/.asdf/shims/ruby

require 'csv'
require 'bundler/inline'

gemfile do
  source "https://rubygems.org"
  gem 'lmdb', '~> 0.6.2'
end

LMDB.new("./database") do |env|
  db = env.database

  IO.popen("zless #{ARGV[0]}", "r") do |pipe|
    pipe.each do |line|
      next if line =~ /^#/
      id, ref = line.split("\t").values_at(*[2, 3])
      env.transaction { db[id] = ref }
      env.transaction { puts id, db[id] }
    end
  end
end
